version: "3"
services:
  pg:
    ports:
      - "5432:5432"
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=homeland_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
